name: yt_player
description: YouTube player plugin for Flutter.
version: 0.0.2
homepage: https://github.com/malviyaritesh/yt_player
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    androidPackage: com.owliverse.yt_player
    pluginClass: YtPlayerPlugin
